import type { CodexThemeV1Payload } from "./theme-system";

export const CODEX_APP_THEME_SOURCE_VERSION = "26.730.61639";

export type BundledCodexTheme = CodexThemeV1Payload & { label: string };

// Extracted from the signed Codex app bundle's registered code-theme modules.
// The catalog keeps Codex's own family ids and only includes variants that the app registers.
export const CODEX_APP_THEME_CATALOG = [
  { codeThemeId: "ayu", label: "Ayu", theme: { accent: "#e6b450", contrast: 60, fonts: { code: null, ui: null }, ink: "#bfbdb6", opaqueWindows: false, semanticColors: { diffAdded: "#70bf56", diffRemoved: "#f26d78", skill: "#d0a1ff" }, surface: "#10141c" }, variant: "dark" },
  { codeThemeId: "catppuccin", label: "Catppuccin", theme: { accent: "#8839ef", contrast: 45, fonts: { code: null, ui: null }, ink: "#4c4f69", opaqueWindows: false, semanticColors: { diffAdded: "#40a02b", diffRemoved: "#d20f39", skill: "#8839ef" }, surface: "#eff1f5" }, variant: "light" },
  { codeThemeId: "catppuccin", label: "Catppuccin", theme: { accent: "#cba6f7", contrast: 60, fonts: { code: null, ui: null }, ink: "#cdd6f4", opaqueWindows: false, semanticColors: { diffAdded: "#a6e3a1", diffRemoved: "#f38ba8", skill: "#cba6f7" }, surface: "#1e1e2e" }, variant: "dark" },
  { codeThemeId: "absolutely", label: "Absolutely", theme: { accent: "#cc7d5e", contrast: 45, fonts: { code: null, ui: null }, ink: "#2d2d2b", opaqueWindows: false, semanticColors: { diffAdded: "#00c853", diffRemoved: "#ff5f38", skill: "#cc7d5e" }, surface: "#f9f9f7" }, variant: "light" },
  { codeThemeId: "absolutely", label: "Absolutely", theme: { accent: "#cc7d5e", contrast: 60, fonts: { code: null, ui: null }, ink: "#f9f9f7", opaqueWindows: false, semanticColors: { diffAdded: "#00c853", diffRemoved: "#ff5f38", skill: "#cc7d5e" }, surface: "#2d2d2b" }, variant: "dark" },
  { codeThemeId: "codex", label: "Codex", theme: { accent: "#0169cc", contrast: 45, fonts: { code: null, ui: null }, ink: "#0d0d0d", opaqueWindows: false, semanticColors: { diffAdded: "#00a240", diffRemoved: "#e02e2a", skill: "#751ed9" }, surface: "#ffffff" }, variant: "light" },
  { codeThemeId: "codex", label: "Codex", theme: { accent: "#0169cc", contrast: 60, fonts: { code: null, ui: null }, ink: "#fcfcfc", opaqueWindows: false, semanticColors: { diffAdded: "#00a240", diffRemoved: "#e02e2a", skill: "#b06dff" }, surface: "#111111" }, variant: "dark" },
  { codeThemeId: "dracula", label: "Dracula", theme: { accent: "#ff79c6", contrast: 60, fonts: { code: null, ui: null }, ink: "#f8f8f2", opaqueWindows: false, semanticColors: { diffAdded: "#50fa7b", diffRemoved: "#ff5555", skill: "#ff79c6" }, surface: "#282a36" }, variant: "dark" },
  { codeThemeId: "everforest", label: "Everforest", theme: { accent: "#93b259", contrast: 45, fonts: { code: null, ui: null }, ink: "#5c6a72", opaqueWindows: false, semanticColors: { diffAdded: "#8da101", diffRemoved: "#f85552", skill: "#df69ba" }, surface: "#fdf6e3" }, variant: "light" },
  { codeThemeId: "everforest", label: "Everforest", theme: { accent: "#a7c080", contrast: 60, fonts: { code: null, ui: null }, ink: "#d3c6aa", opaqueWindows: false, semanticColors: { diffAdded: "#a7c080", diffRemoved: "#e67e80", skill: "#d699b6" }, surface: "#2d353b" }, variant: "dark" },
  { codeThemeId: "github", label: "GitHub", theme: { accent: "#0969da", contrast: 45, fonts: { code: null, ui: null }, ink: "#1f2328", opaqueWindows: false, semanticColors: { diffAdded: "#1a7f37", diffRemoved: "#cf222e", skill: "#8250df" }, surface: "#ffffff" }, variant: "light" },
  { codeThemeId: "github", label: "GitHub", theme: { accent: "#1f6feb", contrast: 60, fonts: { code: null, ui: null }, ink: "#e6edf3", opaqueWindows: false, semanticColors: { diffAdded: "#3fb950", diffRemoved: "#f85149", skill: "#bc8cff" }, surface: "#0d1117" }, variant: "dark" },
  { codeThemeId: "gruvbox", label: "Gruvbox", theme: { accent: "#458588", contrast: 45, fonts: { code: null, ui: null }, ink: "#3c3836", opaqueWindows: false, semanticColors: { diffAdded: "#3c3836", diffRemoved: "#cc241d", skill: "#b16286" }, surface: "#fbf1c7" }, variant: "light" },
  { codeThemeId: "gruvbox", label: "Gruvbox", theme: { accent: "#458588", contrast: 60, fonts: { code: null, ui: null }, ink: "#ebdbb2", opaqueWindows: false, semanticColors: { diffAdded: "#ebdbb2", diffRemoved: "#cc241d", skill: "#b16286" }, surface: "#282828" }, variant: "dark" },
  { codeThemeId: "linear", label: "Linear", theme: { accent: "#5e6ad2", contrast: 45, fonts: { code: null, ui: "Inter" }, ink: "#1b1b1b", opaqueWindows: true, semanticColors: { diffAdded: "#52a450", diffRemoved: "#c94446", skill: "#8160d8" }, surface: "#fcfcfd" }, variant: "light" },
  { codeThemeId: "linear", label: "Linear", theme: { accent: "#606acc", contrast: 60, fonts: { code: null, ui: "Inter" }, ink: "#e3e4e6", opaqueWindows: true, semanticColors: { diffAdded: "#69c967", diffRemoved: "#ff7e78", skill: "#c2a1ff" }, surface: "#0f0f11" }, variant: "dark" },
  { codeThemeId: "lobster", label: "Lobster", theme: { accent: "#ff5c5c", contrast: 60, fonts: { code: null, ui: "Satoshi" }, ink: "#e4e4e7", opaqueWindows: false, semanticColors: { diffAdded: "#22c55e", diffRemoved: "#ff5c5c", skill: "#3b82f6" }, surface: "#111827" }, variant: "dark" },
  { codeThemeId: "material", label: "Material", theme: { accent: "#80cbc4", contrast: 60, fonts: { code: null, ui: null }, ink: "#eeffff", opaqueWindows: false, semanticColors: { diffAdded: "#c3e88d", diffRemoved: "#f07178", skill: "#c792ea" }, surface: "#212121" }, variant: "dark" },
  { codeThemeId: "matrix", label: "Matrix", theme: { accent: "#1eff5a", contrast: 60, fonts: { code: null, ui: "ui-monospace, \"SFMono-Regular\", \"SF Mono\", Menlo, Consolas, \"Liberation Mono\", monospace" }, ink: "#b8ffca", opaqueWindows: true, semanticColors: { diffAdded: "#1eff5a", diffRemoved: "#fa423e", skill: "#1eff5a" }, surface: "#040805" }, variant: "dark" },
  { codeThemeId: "monokai", label: "Monokai", theme: { accent: "#99947c", contrast: 60, fonts: { code: null, ui: null }, ink: "#f8f8f2", opaqueWindows: false, semanticColors: { diffAdded: "#86b42b", diffRemoved: "#c4265e", skill: "#8c6bc8" }, surface: "#272822" }, variant: "dark" },
  { codeThemeId: "night-owl", label: "Night Owl", theme: { accent: "#44596b", contrast: 60, fonts: { code: null, ui: null }, ink: "#d6deeb", opaqueWindows: false, semanticColors: { diffAdded: "#c5e478", diffRemoved: "#ef5350", skill: "#c792ea" }, surface: "#011627" }, variant: "dark" },
  { codeThemeId: "nord", label: "Nord", theme: { accent: "#88c0d0", contrast: 60, fonts: { code: null, ui: null }, ink: "#d8dee9", opaqueWindows: false, semanticColors: { diffAdded: "#a3be8c", diffRemoved: "#bf616a", skill: "#b48ead" }, surface: "#2e3440" }, variant: "dark" },
  { codeThemeId: "notion", label: "Notion", theme: { accent: "#3183d8", contrast: 45, fonts: { code: null, ui: null }, ink: "#37352f", opaqueWindows: true, semanticColors: { diffAdded: "#008000", diffRemoved: "#a31515", skill: "#0000ff" }, surface: "#ffffff" }, variant: "light" },
  { codeThemeId: "notion", label: "Notion", theme: { accent: "#3183d8", contrast: 60, fonts: { code: null, ui: null }, ink: "#d9d9d8", opaqueWindows: true, semanticColors: { diffAdded: "#4ec9b0", diffRemoved: "#fa423e", skill: "#3183d8" }, surface: "#191919" }, variant: "dark" },
  { codeThemeId: "oscurange", label: "Oscurange", theme: { accent: "#f9b98c", contrast: 60, fonts: { code: null, ui: null }, ink: "#e6e6e6", opaqueWindows: false, semanticColors: { diffAdded: "#40c977", diffRemoved: "#fa423e", skill: "#479ffa" }, surface: "#0b0b0f" }, variant: "dark" },
  { codeThemeId: "one", label: "One", theme: { accent: "#526fff", contrast: 45, fonts: { code: null, ui: null }, ink: "#383a42", opaqueWindows: false, semanticColors: { diffAdded: "#3bba54", diffRemoved: "#e45649", skill: "#526fff" }, surface: "#fafafa" }, variant: "light" },
  { codeThemeId: "one", label: "One", theme: { accent: "#4d78cc", contrast: 60, fonts: { code: null, ui: null }, ink: "#abb2bf", opaqueWindows: false, semanticColors: { diffAdded: "#8cc265", diffRemoved: "#e05561", skill: "#c162de" }, surface: "#282c34" }, variant: "dark" },
  { codeThemeId: "proof", label: "Proof", theme: { accent: "#3d755d", contrast: 45, fonts: { code: null, ui: null }, ink: "#2f312d", opaqueWindows: false, semanticColors: { diffAdded: "#3d755d", diffRemoved: "#ba2623", skill: "#5f6ac2" }, surface: "#f5f3ed" }, variant: "light" },
  { codeThemeId: "raycast", label: "Raycast", theme: { accent: "#ff6363", contrast: 45, fonts: { code: "\"Jetbrains Mono\"", ui: "Inter" }, ink: "#030303", opaqueWindows: false, semanticColors: { diffAdded: "#006b4f", diffRemoved: "#b12424", skill: "#9a1b6e" }, surface: "#ffffff" }, variant: "light" },
  { codeThemeId: "raycast", label: "Raycast", theme: { accent: "#ff6363", contrast: 60, fonts: { code: "\"Jetbrains Mono\"", ui: "Inter" }, ink: "#fefefe", opaqueWindows: false, semanticColors: { diffAdded: "#59d499", diffRemoved: "#ff6363", skill: "#cf2f98" }, surface: "#101010" }, variant: "dark" },
  { codeThemeId: "rose-pine", label: "Rose Pine", theme: { accent: "#d7827e", contrast: 45, fonts: { code: null, ui: null }, ink: "#575279", opaqueWindows: false, semanticColors: { diffAdded: "#56949f", diffRemoved: "#797593", skill: "#907aa9" }, surface: "#faf4ed" }, variant: "light" },
  { codeThemeId: "rose-pine", label: "Rose Pine", theme: { accent: "#ea9a97", contrast: 60, fonts: { code: null, ui: null }, ink: "#e0def4", opaqueWindows: false, semanticColors: { diffAdded: "#9ccfd8", diffRemoved: "#908caa", skill: "#c4a7e7" }, surface: "#232136" }, variant: "dark" },
  { codeThemeId: "sentry", label: "Sentry", theme: { accent: "#7055f6", contrast: 60, fonts: { code: null, ui: null }, ink: "#e6dff9", opaqueWindows: false, semanticColors: { diffAdded: "#8ee6d7", diffRemoved: "#fa423e", skill: "#7055f6" }, surface: "#2d2935" }, variant: "dark" },
  { codeThemeId: "solarized", label: "Solarized", theme: { accent: "#b58900", contrast: 45, fonts: { code: null, ui: null }, ink: "#657b83", opaqueWindows: false, semanticColors: { diffAdded: "#859900", diffRemoved: "#dc322f", skill: "#d33682" }, surface: "#fdf6e3" }, variant: "light" },
  { codeThemeId: "solarized", label: "Solarized", theme: { accent: "#d30102", contrast: 60, fonts: { code: null, ui: null }, ink: "#839496", opaqueWindows: false, semanticColors: { diffAdded: "#859900", diffRemoved: "#dc322f", skill: "#d33682" }, surface: "#002b36" }, variant: "dark" },
  { codeThemeId: "tokyo-night", label: "Tokyo Night", theme: { accent: "#3d59a1", contrast: 60, fonts: { code: null, ui: null }, ink: "#a9b1d6", opaqueWindows: false, semanticColors: { diffAdded: "#449dab", diffRemoved: "#914c54", skill: "#9d7cd8" }, surface: "#1a1b26" }, variant: "dark" },
  { codeThemeId: "temple", label: "Temple", theme: { accent: "#e4f222", contrast: 60, fonts: { code: null, ui: null }, ink: "#c7e6da", opaqueWindows: false, semanticColors: { diffAdded: "#40c977", diffRemoved: "#fa423e", skill: "#e4f222" }, surface: "#02120c" }, variant: "dark" },
  { codeThemeId: "vercel", label: "Vercel", theme: { accent: "#006aff", contrast: 40, fonts: { code: "\"Geist Mono\", ui-monospace, \"SFMono-Regular\"", ui: "Geist, Inter" }, ink: "#171717", opaqueWindows: true, semanticColors: { diffAdded: "#28A948", diffRemoved: "#EB001D", skill: "#A100F8" }, surface: "#ffffff" }, variant: "light" },
  { codeThemeId: "vercel", label: "Vercel", theme: { accent: "#006efe", contrast: 50, fonts: { code: "\"Geist Mono\", ui-monospace, \"SFMono-Regular\"", ui: "Geist, Inter" }, ink: "#ededed", opaqueWindows: true, semanticColors: { diffAdded: "#00AD3A", diffRemoved: "#F13342", skill: "#9540D5" }, surface: "#000000" }, variant: "dark" },
  { codeThemeId: "vscode-plus", label: "VS Code Plus", theme: { accent: "#007acc", contrast: 45, fonts: { code: null, ui: null }, ink: "#000000", opaqueWindows: false, semanticColors: { diffAdded: "#008000", diffRemoved: "#ee0000", skill: "#0000ff" }, surface: "#ffffff" }, variant: "light" },
  { codeThemeId: "vscode-plus", label: "VS Code Plus", theme: { accent: "#007acc", contrast: 60, fonts: { code: null, ui: null }, ink: "#d4d4d4", opaqueWindows: false, semanticColors: { diffAdded: "#369432", diffRemoved: "#f44747", skill: "#000080" }, surface: "#1e1e1e" }, variant: "dark" },
  { codeThemeId: "xcode", label: "Xcode", theme: { accent: "#0e0eff", contrast: 45, fonts: { code: "\"SFMono-Regular\"", ui: null }, ink: "#1a1c1f", opaqueWindows: false, semanticColors: { diffAdded: "#00a240", diffRemoved: "#c41a16", skill: "#0e0eff" }, surface: "#ffffff" }, variant: "light" },
  { codeThemeId: "xcode", label: "Xcode", theme: { accent: "#5482ff", contrast: 60, fonts: { code: "\"SFMono-Medium\"", ui: null }, ink: "#ffffff", opaqueWindows: false, semanticColors: { diffAdded: "#67b7a4", diffRemoved: "#fc6a5d", skill: "#5482ff" }, surface: "#1f1f24" }, variant: "dark" },
] as const satisfies readonly BundledCodexTheme[];
