export type ShellLocale = "en" | "zh-CN";

export const NEW_TASK_COPY = {
  en: {
    heading: "Create a new Task",
    titleLabel: "Task title",
    titlePlaceholder: "What should the Agent work on?",
    descriptionLabel: "Description",
    descriptionPlaceholder: "Add context, constraints, or the desired outcome (optional)",
    project: "Project context",
    noProject: "No Project",
    clear: "Clear draft",
    create: "Create Task",
    creating: "Creating Task…",
    invalidTitle: "Enter a Task title.",
    projectLoadFailed: "Projects could not be loaded. You can still create a Task without Project context.",
  },
  "zh-CN": {
    heading: "新建 Task",
    titleLabel: "Task 标题",
    titlePlaceholder: "希望 Agent 处理什么？",
    descriptionLabel: "描述",
    descriptionPlaceholder: "补充上下文、约束或期望结果（可选）",
    project: "Project 上下文",
    noProject: "无 Project",
    clear: "清空草稿",
    create: "创建 Task",
    creating: "正在创建 Task…",
    invalidTitle: "请输入 Task 标题。",
    projectLoadFailed: "无法加载 Project。仍可创建不附带 Project 上下文的 Task。",
  },
} as const;

export const TASK_DETAIL_COPY = {
  en: {
    back: "Tasks", title: "Title", description: "Description", save: "Save", saving: "Saving…",
    project: "Project context", noProject: "No Project", issue: "Issue context", noIssue: "No Issue",
    issueUnavailable: "Issue is currently unavailable", updated: "Updated", invalidTitle: "Enter a Task title.",
  },
  "zh-CN": {
    back: "任务", title: "标题", description: "描述", save: "保存", saving: "保存中…",
    project: "Project 上下文", noProject: "无 Project", issue: "Issue 上下文", noIssue: "无 Issue",
    issueUnavailable: "Issue 当前不可用", updated: "更新时间", invalidTitle: "请输入 Task 标题。",
  },
} as const;

export const ISSUE_COPY = {
  en: {
    issues: "Issues", selectProjectHelp: "Select a Project first, then browse one provider at a time.", selectProject: "Select Project…",
    selectProjectTitle: "Select a Project", selectProjectDescription: "Mystra will not request GitHub or Linear Issues without an explicit Project scope.",
    overview: "Overview", settings: "Settings", projectScope: "Project-scoped repository and Issue sources",
    sourceUnavailable: "Issue source unavailable", sourceUnavailableHelp: "The configured provider source could not be resolved. Mystra did not fall back to another connection.",
    sourcesUnavailable: "Issue sources unavailable", loadingSources: "Loading Issue sources…", retry: "Retry", refresh: "Refresh",
    linearMissing: "Linear source is not configured", linearMissingHelp: "Open the Project Settings tab to select an exact Linear connection and Team.",
    noFallback: "No workspace-wide fallback", derivedRepository: "Derived from Project repository", exactTeamScope: "Exact Linear Team scope",
    loadingIssues: "Loading Issues…", loadFailed: "Could not load Issues", noIssues: "No Issues found", noIssuesHelp: "The current provider scope and filters returned no rows.",
    previous: "Previous", next: "Next", page: "Page", cursorIndependent: "provider cursor retained independently",
    open: "Open", closed: "Closed", allStates: "All states", assignee: "Assignee", label: "Label", milestone: "Milestone",
    allPriorities: "All priorities", noPriority: "No priority", urgent: "Urgent", high: "High", medium: "Medium", low: "Low", statusId: "Status ID", assigneeId: "Assignee ID", cycleId: "Cycle ID",
    githubHeaders: ["Number", "Title", "State", "Assignees", "Labels", "Milestone", "Updated"],
    linearHeaders: ["Identifier", "Title", "Status", "Priority", "Assignee", "Cycle", "Updated"],
    createTask: "Create Task", creatingTask: "Creating…", openTask: "Open Task", retryTask: "Retry", taskCreateFailed: "Task creation failed",
  },
  "zh-CN": {
    issues: "议题", selectProjectHelp: "先选择一个 Project，再一次浏览一个 provider。", selectProject: "选择 Project…",
    selectProjectTitle: "先选择 Project", selectProjectDescription: "没有明确的 Project 范围时，Mystra 不会请求 GitHub 或 Linear Issue。",
    overview: "概览", settings: "设置", projectScope: "Project 范围内的仓库与 Issue 来源",
    sourceUnavailable: "Issue 来源不可用", sourceUnavailableHelp: "已配置的 provider 来源无法解析。Mystra 没有回退到其他连接。",
    sourcesUnavailable: "Issue 来源不可用", loadingSources: "正在加载 Issue 来源…", retry: "重试", refresh: "刷新",
    linearMissing: "尚未配置 Linear 来源", linearMissingHelp: "请在 Project 的设置 tab 中选择 exact Linear connection 和 Team。",
    noFallback: "不会回退到整个 workspace", derivedRepository: "由 Project repository 自动派生", exactTeamScope: "精确 Linear Team 范围",
    loadingIssues: "正在加载 Issue…", loadFailed: "无法加载 Issue", noIssues: "没有找到 Issue", noIssuesHelp: "当前 provider 范围和筛选条件没有返回数据。",
    previous: "上一页", next: "下一页", page: "第", cursorIndependent: "provider 游标独立保留",
    open: "开放", closed: "已关闭", allStates: "全部状态", assignee: "负责人", label: "标签", milestone: "里程碑",
    allPriorities: "全部优先级", noPriority: "无优先级", urgent: "紧急", high: "高", medium: "中", low: "低", statusId: "状态 ID", assigneeId: "负责人 ID", cycleId: "周期 ID",
    githubHeaders: ["编号", "标题", "状态", "负责人", "标签", "里程碑", "更新时间"],
    linearHeaders: ["标识", "标题", "状态", "优先级", "负责人", "周期", "更新时间"],
    createTask: "创建 Task", creatingTask: "创建中…", openTask: "打开 Task", retryTask: "重试", taskCreateFailed: "Task 创建失败",
  },
} as const;

export const SHELL_COPY = {
  en: {
    account: "Account",
    accountAuthentication: "Sign-in",
    accountAuthenticationDescription: "Caller sign-in is outside the current private MVP.",
    accountProfile: "Operator profile",
    accountProfileDescription: "Identity used for this private control-plane deployment.",
    accountProfileValue: "Local operator",
    appearance: "Appearance",
    actions: "Actions",
    automations: "Automations",
    closeSearch: "Close search",
    collapseSidebar: "Collapse sidebar",
    expandSidebar: "Expand sidebar",
    closeSettings: "Close settings",
    inbox: "Inbox",
    integrations: "Integrations",
    githubApp: "GitHub App",
    githubConnect: "Connect",
    githubReconnect: "Reconnect",
    githubConnectedAs: "Connected as",
    githubDisconnected: "Connect a GitHub App installation to select repositories.",
    githubNotConfigured: "GitHub App deployment settings are incomplete.",
    githubConnectionError: "Connection status could not be loaded.",
    issues: "Issues",
    language: "Language",
    languageDescription: "Choose the shell interface language.",
    languageEnglish: "English",
    languageChinese: "简体中文",
    new: "New",
    newTask: "Create New Task",
    noSearchResults: "No matching tasks",
    noTasksToSearch: "No tasks to search",
    noTasks: "No tasks yet",
    openTask: "Open Task",
    previewSearch: "Select a task to preview",
    projects: "Projects",
    repository: "Repository",
    runtimes: "Runtimes",
    search: "Search",
    searchPlaceholder: "Search tasks",
    sessions: "Sessions",
    settings: "Settings",
    settingsUnavailable: "Not available",
    showAll: "Show All",
    tasks: "Tasks",
    theme: "Theme",
    themeDescription: "Choose the visual theme used by this browser.",
    themeMode: "Theme mode",
    themeModeDescription: "Follow the operating system or force a light or dark appearance.",
    system: "System",
    light: "Light",
    dark: "Dark",
    lightTheme: "Light theme",
    lightThemeDescription: "Theme used whenever the active appearance is light.",
    darkTheme: "Dark theme",
    darkThemeDescription: "Theme used whenever the active appearance is dark.",
    borderMode: "Borders",
    borderModeDescription: "Increase separation between surfaces without changing layout.",
    borderDefault: "Default",
    borderHighContrast: "High contrast",
    borderColorHighContrast: "Color contrast",
    codeSurface: "Code surface",
    codeSurfaceDescription: "Choose an independent light or dark surface for code and terminal content.",
    themeDetails: "Theme details",
    themeDetailsDescription: "Fine-tune contrast and typography for this browser.",
    contrast: "Contrast",
    uiFont: "UI font",
    contentFont: "Content font",
    codeFont: "Code font",
    uiFontSize: "UI font size",
    contentFontSize: "Content font size",
    resetThemeDetails: "Reset details",
    team: "Team",
    teamAdministration: "Team administration",
    teamAdministrationDescription: "Hosted Team administration is outside the current private MVP.",
    teamScope: "Current Team scope",
    teamScopeDescription: "Mystra uses Team as the tenant boundary; workspace is reserved for Session execution.",
    teamScopeValue: "Single private Team",
    updated: "Updated",
  },
  "zh-CN": {
    account: "账户",
    accountAuthentication: "登录",
    accountAuthenticationDescription: "调用方登录不在当前私有 MVP 范围内。",
    accountProfile: "操作者资料",
    accountProfileDescription: "当前私有控制面部署使用的操作者身份。",
    accountProfileValue: "本地操作者",
    appearance: "外观",
    actions: "操作",
    automations: "自动化",
    closeSearch: "关闭搜索",
    collapseSidebar: "收起侧边栏",
    expandSidebar: "展开侧边栏",
    closeSettings: "关闭设置",
    inbox: "收件箱",
    integrations: "集成",
    githubApp: "GitHub App",
    githubConnect: "连接",
    githubReconnect: "重新连接",
    githubConnectedAs: "已连接账户",
    githubDisconnected: "连接 GitHub App installation 后才能选择仓库。",
    githubNotConfigured: "GitHub App 部署配置不完整。",
    githubConnectionError: "无法加载连接状态。",
    issues: "议题",
    language: "语言",
    languageDescription: "选择框架界面语言。",
    languageEnglish: "English",
    languageChinese: "简体中文",
    new: "新建",
    newTask: "新建 Task",
    noSearchResults: "没有匹配的任务",
    noTasksToSearch: "暂无可搜索的 Task",
    noTasks: "暂无任务",
    openTask: "打开 Task",
    previewSearch: "选择一个 Task 以预览",
    projects: "项目",
    repository: "Repository",
    runtimes: "运行环境",
    search: "搜索",
    searchPlaceholder: "搜索任务",
    sessions: "Sessions",
    settings: "设置",
    settingsUnavailable: "暂不可用",
    showAll: "显示全部",
    tasks: "任务",
    theme: "主题",
    themeDescription: "选择此浏览器使用的界面主题。",
    themeMode: "明暗模式",
    themeModeDescription: "跟随操作系统，或固定使用明亮 / 暗色外观。",
    system: "跟随系统",
    light: "明亮",
    dark: "暗色",
    lightTheme: "明亮主题",
    lightThemeDescription: "当前外观为明亮模式时使用的主题。",
    darkTheme: "暗色主题",
    darkThemeDescription: "当前外观为暗色模式时使用的主题。",
    borderMode: "边框",
    borderModeDescription: "在不改变布局的情况下增强界面层次。",
    borderDefault: "默认",
    borderHighContrast: "高对比",
    borderColorHighContrast: "彩色高对比",
    codeSurface: "代码表面",
    codeSurfaceDescription: "为代码与终端内容独立选择明亮或暗色表面。",
    themeDetails: "主题细节",
    themeDetailsDescription: "微调此浏览器中的对比度和字体。",
    contrast: "对比度",
    uiFont: "界面字体",
    contentFont: "内容字体",
    codeFont: "代码字体",
    uiFontSize: "界面字号",
    contentFontSize: "内容字号",
    resetThemeDetails: "重置细节",
    team: "团队",
    teamAdministration: "Team 管理",
    teamAdministrationDescription: "托管式 Team 管理不在当前私有 MVP 范围内。",
    teamScope: "当前 Team 范围",
    teamScopeDescription: "Mystra 使用 Team 表示租户边界；workspace 保留给 Session 执行目录。",
    teamScopeValue: "单一私有 Team",
    updated: "更新时间",
  },
} as const;
