export type ShellLocale = "en" | "zh-CN";

export const SHELL_COPY = {
  en: {
    account: "Account",
    accountAuthentication: "Sign-in",
    accountAuthenticationDescription: "Caller sign-in is outside the current private MVP.",
    accountProfile: "Operator profile",
    accountProfileDescription: "Identity used for this private control-plane deployment.",
    accountProfileValue: "Local operator",
    appearance: "Appearance",
    actions: "Actions",
    automations: "Automations",
    closeSearch: "Close search",
    collapseSidebar: "Collapse sidebar",
    expandSidebar: "Expand sidebar",
    closeSettings: "Close settings",
    inbox: "Inbox",
    integrations: "Integrations",
    githubApp: "GitHub App",
    githubConnect: "Connect",
    githubReconnect: "Reconnect",
    githubConnectedAs: "Connected as",
    githubDisconnected: "Connect a GitHub App installation to select repositories.",
    githubNotConfigured: "GitHub App deployment settings are incomplete.",
    githubConnectionError: "Connection status could not be loaded.",
    issues: "Issues",
    language: "Language",
    languageDescription: "Choose the shell interface language.",
    languageEnglish: "English",
    languageChinese: "简体中文",
    new: "New",
    newTask: "Create New Task",
    noSearchResults: "No matching tasks",
    noTasksToSearch: "No tasks to search",
    noTasks: "No tasks yet",
    openTask: "Open Task",
    previewSearch: "Select a task to preview",
    projects: "Projects",
    repository: "Repository",
    search: "Search",
    searchPlaceholder: "Search tasks",
    sessions: "Sessions",
    settings: "Settings",
    settingsUnavailable: "Not available",
    showAll: "Show All",
    tasks: "Tasks",
    theme: "Theme",
    themeDescription: "Choose the visual theme used by this browser.",
    themeMode: "Theme mode",
    themeModeDescription: "Follow the operating system or force a light or dark appearance.",
    system: "System",
    light: "Light",
    dark: "Dark",
    lightTheme: "Light theme",
    lightThemeDescription: "Theme used whenever the active appearance is light.",
    darkTheme: "Dark theme",
    darkThemeDescription: "Theme used whenever the active appearance is dark.",
    borderMode: "Borders",
    borderModeDescription: "Increase separation between surfaces without changing layout.",
    borderDefault: "Default",
    borderHighContrast: "High contrast",
    borderColorHighContrast: "Color contrast",
    codeSurface: "Code surface",
    codeSurfaceDescription: "Choose an independent light or dark surface for code and terminal content.",
    themeDetails: "Theme details",
    themeDetailsDescription: "Fine-tune contrast and typography for this browser.",
    contrast: "Contrast",
    uiFont: "UI font",
    contentFont: "Content font",
    codeFont: "Code font",
    uiFontSize: "UI font size",
    contentFontSize: "Content font size",
    resetThemeDetails: "Reset details",
    team: "Team",
    teamAdministration: "Team administration",
    teamAdministrationDescription: "Hosted Team administration is outside the current private MVP.",
    teamScope: "Current Team scope",
    teamScopeDescription: "Mystra uses Team as the tenant boundary; workspace is reserved for Session execution.",
    teamScopeValue: "Single private Team",
    updated: "Updated",
  },
  "zh-CN": {
    account: "账户",
    accountAuthentication: "登录",
    accountAuthenticationDescription: "调用方登录不在当前私有 MVP 范围内。",
    accountProfile: "操作者资料",
    accountProfileDescription: "当前私有控制面部署使用的操作者身份。",
    accountProfileValue: "本地操作者",
    appearance: "外观",
    actions: "操作",
    automations: "自动化",
    closeSearch: "关闭搜索",
    collapseSidebar: "收起侧边栏",
    expandSidebar: "展开侧边栏",
    closeSettings: "关闭设置",
    inbox: "收件箱",
    integrations: "集成",
    githubApp: "GitHub App",
    githubConnect: "连接",
    githubReconnect: "重新连接",
    githubConnectedAs: "已连接账户",
    githubDisconnected: "连接 GitHub App installation 后才能选择仓库。",
    githubNotConfigured: "GitHub App 部署配置不完整。",
    githubConnectionError: "无法加载连接状态。",
    issues: "议题",
    language: "语言",
    languageDescription: "选择框架界面语言。",
    languageEnglish: "English",
    languageChinese: "简体中文",
    new: "新建",
    newTask: "新建 Task",
    noSearchResults: "没有匹配的任务",
    noTasksToSearch: "暂无可搜索的 Task",
    noTasks: "暂无任务",
    openTask: "打开 Task",
    previewSearch: "选择一个 Task 以预览",
    projects: "项目",
    repository: "Repository",
    search: "搜索",
    searchPlaceholder: "搜索任务",
    sessions: "Sessions",
    settings: "设置",
    settingsUnavailable: "暂不可用",
    showAll: "显示全部",
    tasks: "任务",
    theme: "主题",
    themeDescription: "选择此浏览器使用的界面主题。",
    themeMode: "明暗模式",
    themeModeDescription: "跟随操作系统，或固定使用明亮 / 暗色外观。",
    system: "跟随系统",
    light: "明亮",
    dark: "暗色",
    lightTheme: "明亮主题",
    lightThemeDescription: "当前外观为明亮模式时使用的主题。",
    darkTheme: "暗色主题",
    darkThemeDescription: "当前外观为暗色模式时使用的主题。",
    borderMode: "边框",
    borderModeDescription: "在不改变布局的情况下增强界面层次。",
    borderDefault: "默认",
    borderHighContrast: "高对比",
    borderColorHighContrast: "彩色高对比",
    codeSurface: "代码表面",
    codeSurfaceDescription: "为代码与终端内容独立选择明亮或暗色表面。",
    themeDetails: "主题细节",
    themeDetailsDescription: "微调此浏览器中的对比度和字体。",
    contrast: "对比度",
    uiFont: "界面字体",
    contentFont: "内容字体",
    codeFont: "代码字体",
    uiFontSize: "界面字号",
    contentFontSize: "内容字号",
    resetThemeDetails: "重置细节",
    team: "团队",
    teamAdministration: "Team 管理",
    teamAdministrationDescription: "托管式 Team 管理不在当前私有 MVP 范围内。",
    teamScope: "当前 Team 范围",
    teamScopeDescription: "Mystra 使用 Team 表示租户边界；workspace 保留给 Session 执行目录。",
    teamScopeValue: "单一私有 Team",
    updated: "更新时间",
  },
} as const;
